<?php return array(
    'root' => array(
        'name' => 'rockett/textformatter-typographer',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'df7b76eb1446f764f89cee9adde529b857666d2b',
        'type' => 'processwire-module',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v2.2.0',
            'version' => '2.2.0.0',
            'reference' => 'c29dc4b93137acb82734f672c37e029dfbd95b35',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.8.0',
            'version' => '2.8.0.0',
            'reference' => '3c5d5a56d56f48a1ca08a0670f0f80c1dad368f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mundschenk-at/php-typography' => array(
            'pretty_version' => 'v6.7.0',
            'version' => '6.7.0.0',
            'reference' => '6b0414811f42e53e101f5ea5a8023c63eafd3dcb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mundschenk-at/php-typography',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rockett/textformatter-typographer' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'df7b76eb1446f764f89cee9adde529b857666d2b',
            'type' => 'processwire-module',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
